# SPDX-FileCopyrightText: 2026 PlainLicense
#
# SPDX-License-Identifier: LicenseRef-PlainMIT OR MIT

[tools]
ruff = "latest"
tombi = "latest"
ty = "latest"
typos = "latest"
uv = "latest"
"pipx:exportify" = "latest"
"pipx:reuse" = "latest"
bun = "latest"
wrangler = "latest"
node = "24"
python = "3.13"
